server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # 사용자가 /login, /home 등 어떤 경로로 들어와도
        # 실제 파일이 없으면 index.html을 대신 보여줌. (SPA 라우팅 필수)
        try_files $uri $uri/ /index.html;
    }

    # 에러 페이지 처리
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}