spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # .env-dev에 적힌 개발용 변수들을 사용
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/gguljob_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: ${REDIS_HOST:gguljob-redis-dev}
      port: ${REDIS_PORT:6379}

  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2

cdn:
  url: ${CDN_URL}
  