spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # .env-prod에 적힌 운영용 변수들을 사용
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # 운영 서버에서 테이블 변경 절대 금지
    show-sql: false # 운영 로그에서 SQL 숨김 (보안)

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

# ★ 운영 환경에서 Swagger UI 비활성화 (보안)
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

cdn:
  url: ${CDN_URL}
